<?php

use Doctrine\ORM\EntityRepository;

/**
 * UserWidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dashboard_Entity_Repository_UserWidget extends EntityRepository
{
}