<?php

use Doctrine\ORM\EntityRepository;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dashboard_Entity_Repository_Widget extends EntityRepository
{
}